# Generated by Django 6.1.1 on 2026-09-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_description',
        ),
    ]
