# Generated by Django 6.1.1 on 2026-09-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_colorvariation_sizevariation_product_color_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_variation',
            field=models.ManyToManyField(blank=True, to='products.colorvariation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_variation',
            field=models.ManyToManyField(blank=True, to='products.sizevariation'),
        ),
    ]
